# Generated by Django 4.2 on 2023-04-20 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_net', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='address',
        ),
        migrations.AddField(
            model_name='factory',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trade_net.address'),
        ),
    ]
